- lights:
  - id : 0
    x: 13.5
    y: 21.2
    z: 2.5  

  - id : 1
    x: 11.1
    y: 21.2
    z: 2.5
  
  - id : 2
    x: 8.7
    y: 21.2
    z: 2.5
  
  - id : 3
    x: 5.7
    y: 21.2
    z: 2.5
  
  - id : 4
    x: 3.3
    y: 21.2
    z: 2.5
  
  - id : 5
    x: 0.9
    y: 21.2
    z: 2.5
  
  - id : 6
    x: 13.5
    y: 18.8
    z: 2.5
  
  - id : 7
    x: 11.1
    y: 18.8
    z: 2.5
  
  - id : 8
    x: 8.7
    y: 18.8
    z: 2.5
  
  - id : 9
    x: 5.7
    y: 18.8
    z: 2.5

  - id : 10
    x: 3.3
    y: 18.8
    z: 2.5
  
  - id : 11
    x: 0.9
    y: 18.8
    z: 2.5

  - id : 12
    x: 13.5
    y: 16.4
    z: 2.5
  
  - id : 13
    x: 11.1
    y: 16.4
    z: 2.5
  
  - id : 14
    x: 8.7
    y: 16.4
    z: 2.5

  - id : 15
    x: 5.7
    y: 16.4
    z: 2.5
  
  - id : 16
    x: 3.3
    y: 16.4
    z: 2.5

  - id : 17
    x: 0.9
    y: 16.4
    z: 2.5
  
  - id : 18
    x: 13.5
    y: 14.0
    z: 2.5
  
  - id : 19
    x: 11.1
    y: 14.0
    z: 2.5
  
  - id : 20
    x: 8.7
    y: 14.0
    z: 2.5

  - id : 21
    x: 5.7
    y: 14.0
    z: 2.5
  
  - id : 22
    x: 3.3
    y: 14.0
    z: 2.5
  
  - id : 23
    x: 0.9
    y: 14.0
    z: 2.5

  - id : 24
    x: 13.5
    y: 11.6
    z: 2.5
  
  - id : 25
    x: 11.1
    y: 11.6
    z: 2.5
  
  - id : 26
    x: 8.7
    y: 11.6
    z: 2.5
  
  - id : 27
    x: 5.7
    y: 11.6
    z: 2.5
  
  - id : 28
    x: 3.3
    y: 11.6
    z: 2.5
  
  - id : 29
    x: 0.9
    y: 11.6
    z: 2.5
  
  - id : 30
    x: 13.5
    y: 9.2
    z: 2.5
  
  - id : 31
    x: 11.1
    y: 9.2
    z: 2.5
  
  - id: 32
    x: 8.7
    y: 9.2
    z: 2.5
  
  - id: 33
    x: 5.7
    y: 9.2
    z: 2.5
  
  - id: 34
    x: 3.3
    y: 9.2
    z: 2.5
  
  - id: 35
    x: 0.9
    y: 9.2
    z: 2.5
  
  - id: 36
    x: 13.5
    y: 6.8
    z: 2.5
  
  - id: 37
    x: 11.1
    y: 6.8
    z: 2.5
  
  - id: 38
    x: 8.7
    y: 6.8
    z: 2.5
  
  - id: 39
    x: 5.7
    y: 6.8
    z: 2.5
  
  - id: 40
    x: 3.3
    y: 6.8
    z: 2.5
  
  - id: 41
    x: 0.9
    y: 6.8
    z: 2.5
  
  - id: 42
    x: 13.5
    y: 4.4
    z: 2.5
  
  - id: 43
    x: 11.1
    y: 4.4
    z: 2.5
  
  - id: 44
    x: 8.7
    y: 4.4
    z: 2.5
  
  - id: 45
    x: 5.7
    y: 4.4
    z: 2.5
  
  - id: 46
    x: 3.3
    y: 4.4
    z: 2.5
  
  - id: 47
    x: 0.9
    y: 4.4
    z: 2.5
  
  - id: 48
    x: 13.5
    y: 2.6
    z: 2.5
  
  - id: 49
    x: 11.1
    y: 2.6
    z: 2.5
  
  - id: 50
    x: 8.7
    y: 2.6
    z: 2.5
  
  - id: 51
    x: 5.7
    y: 2.6
    z: 2.5
  
  - id: 52
    x: 3.3
    y: 2.6
    z: 2.5
  
  - id: 53
    x: 0.9
    y: 2.6
    z: 2.5

- speakers:
  
    - id: 0
      x: 6.7
      y: 0.
      z: 2.5
  
    - id: 1
      x: 14.65
      y: 4.20
      z: 2.5

    - id: 2
      x: 14.65
      y: 7.7
      z: 2.5

    - id: 3
      x: 14.65
      y: 11.0
      z: 2.5

    - id: 4
      x: 14.65
      y: 14.7
      z: 2.5

    - id: 5
      x: 6.7
      y: 22.7
      z: 2.5
    
    - id: 6
      x: 0.
      y: 14.7
      z: 2.5
    
    - id: 7
      x: 0.
      y: 11.0
      z: 2.5
    
    - id: 8
      x: 0.
      y: 7.7
      z: 2.5
    
    - id: 9
      x: 0.
      y: 4.2
      z: 2.5
    

  
 
  
  
  
